# coding: utf-8

"""
    LILT API

    LILT API Support: https://lilt.atlassian.net/servicedesk/customer/portals    The LILT API enables programmatic access to the full-range of LILT backend services including:   * Training of and translating with interactive, adaptive machine translation   * Large-scale translation memory   * The Lexicon (a large-scale termbase)   * Programmatic control of the LILT CAT environment   * Translation memory synchronization  Requests and responses are in JSON format. The REST API only responds to HTTPS / SSL requests.  The base url for this REST API is `https://api.lilt.com/`.  ## Authentication  Requests are authenticated via API key, which requires the Business plan.  Requests are authenticated using [HTTP Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication). Add your API key as both the `username` and `password`.  For development, you may also pass the API key via the `key` query parameter. This is less secure than HTTP Basic Auth, and is not recommended for production use.  ## Quotas  Our services have a general quota of 4000 requests per minute. Should you hit the maximum requests per minute, you will need to wait 60 seconds before you can send another request. 

    The version of the OpenAPI document: v3.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lilt.api.jobs_api import JobsApi


class TestJobsApi(unittest.TestCase):
    """JobsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = JobsApi()

    def tearDown(self) -> None:
        pass

    def test_archive_job(self) -> None:
        """Test case for archive_job

        Archive a Job
        """
        pass

    def test_create_job(self) -> None:
        """Test case for create_job

        Create a Job
        """
        pass

    def test_delete_job(self) -> None:
        """Test case for delete_job

        Delete a Job
        """
        pass

    def test_deliver_job(self) -> None:
        """Test case for deliver_job

        Deliver a Job
        """
        pass

    def test_download_job(self) -> None:
        """Test case for download_job

        Download a Job
        """
        pass

    def test_export_job(self) -> None:
        """Test case for export_job

        Export a Job
        """
        pass

    def test_get_job(self) -> None:
        """Test case for get_job

        Retrieve a Job
        """
        pass

    def test_get_job_leverage_stats(self) -> None:
        """Test case for get_job_leverage_stats

        Retrieve Job Leverage Stats
        """
        pass

    def test_reactivate_job(self) -> None:
        """Test case for reactivate_job

        Reactivate a Job
        """
        pass

    def test_retrieve_all_jobs(self) -> None:
        """Test case for retrieve_all_jobs

        Retrieve all Jobs
        """
        pass

    def test_unarchive_job(self) -> None:
        """Test case for unarchive_job

        Unarchive a Job
        """
        pass

    def test_update_job(self) -> None:
        """Test case for update_job

        Update a Job
        """
        pass


if __name__ == '__main__':
    unittest.main()
