# This workflow will regenerate the client library API bindings based on the
# public OpenAPI spec.

name: OpenAPI Generator

on:
  workflow_dispatch:
    inputs: null
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: WyriHaximus/github-action-get-previous-tag@0.2.0
        id: latest
      - name: Generate API Bindings
        uses: docker://openapitools/openapi-generator-cli:v4.3.1
        env:
          VERSION: ${{ steps.latest.outputs.tag }}
        with:
          entrypoint: docker-entrypoint.sh
          args: |
            generate
              -i https://beta.lilt.com/docs/api/public-http-api-swagger.yaml
              -g python
              -p packageName=lilt
              -p projectName=lilt-python
              -p packageUrl=https://github.com/lilt/lilt-python
              -p packageVersion=$VERSION
              --git-user-id lilt
              --git-repo-id lilt-python
              -o .
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.3.0
        with:
          commit-message: Regenerates API Bindings
          title: "OpenAPI: Regenerates API Bindings"
          body: |
            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: openapi-bindings
