# This workflow will regenerate the client library API bindings based on the
# public OpenAPI spec.

name: OpenAPI Generator

on:
  workflow_dispatch:
  repository_dispatch:
    types: [API-DocumentationV3-Deployment]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: WyriHaximus/github-action-get-previous-tag@0.2.0
        id: latest
      - name: Generate API Bindings
        uses: docker://openapitools/openapi-generator-cli:v4.3.1
        with:
          args: >-
            generate
            -i https://developers.lilt.com/redocusaurus/plugin-redoc-0.yaml
            -g python
            -p packageName=lilt
            -p projectName=lilt-python
            -p packageUrl=https://github.com/lilt/lilt-python
            -p packageVersion=${{ steps.latest.outputs.tag }}
            --git-user-id lilt
            --git-repo-id lilt-python
            --skip-validate-spec
            -o .
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.2.4
        with:
          commit-message: Regenerates API Bindings
          title: "OpenAPI: Regenerates API Bindings"
          body: |
            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: openapi-bindings
